export const COUNTRIES = [
  { value: "Argentina", label: "Argentina (+54)" },
  { value: "Australia", label: "Australia (+61)" },
  { value: "Bangladesh", label: "Bangladesh (+880)" },
  { value: "Brazil", label: "Brazil (+55)" },
  { value: "Canada", label: "Canada (+1)" },
  { value: "China", label: "China (+86)" },
  { value: "Colombia", label: "Colombia (+57)" },
  { value: "Egypt", label: "Egypt (+20)" },
  { value: "France", label: "France (+33)" },
  { value: "Germany", label: "Germany (+49)" },
  { value: "India", label: "India (+91)" },
  { value: "Indonesia", label: "Indonesia (+62)" },
  { value: "Ireland", label: "Ireland (+353)" },
  { value: "Italy", label: "Italy (+39)" },
  { value: "Japan", label: "Japan (+81)" },
  { value: "Kenya", label: "Kenya (+254)" },
  { value: "Malaysia", label: "Malaysia (+60)" },
  { value: "Mexico", label: "Mexico (+52)" },
  { value: "Netherlands", label: "Netherlands (+31)" },
  { value: "New Zealand", label: "New Zealand (+64)" },
  { value: "Nigeria", label: "Nigeria (+234)" },
  { value: "Pakistan", label: "Pakistan (+92)" },
  { value: "Philippines", label: "Philippines (+63)" },
  { value: "Poland", label: "Poland (+48)" },
  { value: "Russia", label: "Russia (+7)" },
  { value: "Saudi Arabia", label: "Saudi Arabia (+966)" },
  { value: "Singapore", label: "Singapore (+65)" },
  { value: "South Africa", label: "South Africa (+27)" },
  { value: "South Korea", label: "South Korea (+82)" },
  { value: "Spain", label: "Spain (+34)" },
  { value: "Sweden", label: "Sweden (+46)" },
  { value: "Switzerland", label: "Switzerland (+41)" },
  { value: "Thailand", label: "Thailand (+66)" },
  { value: "Turkey", label: "Turkey (+90)" },
  { value: "UAE", label: "UAE (+971)" },
  { value: "United Kingdom", label: "United Kingdom (+44)" },
  { value: "United States", label: "United States (+1)" },
  { value: "Vietnam", label: "Vietnam (+84)" },
];
