export const COUNTRIES = [
  { value: "ar", label: "Argentina (+54)" },
  { value: "au", label: "Australia (+61)" },
  { value: "bd", label: "Bangladesh (+880)" },
  { value: "br", label: "Brazil (+55)" },
  { value: "ca", label: "Canada (+1)" },
  { value: "cn", label: "China (+86)" },
  { value: "co", label: "Colombia (+57)" },
  { value: "eg", label: "Egypt (+20)" },
  { value: "fr", label: "France (+33)" },
  { value: "de", label: "Germany (+49)" },
  { value: "in", label: "India (+91)" },
  { value: "id", label: "Indonesia (+62)" },
  { value: "ie", label: "Ireland (+353)" },
  { value: "it", label: "Italy (+39)" },
  { value: "jp", label: "Japan (+81)" },
  { value: "ke", label: "Kenya (+254)" },
  { value: "my", label: "Malaysia (+60)" },
  { value: "mx", label: "Mexico (+52)" },
  { value: "nl", label: "Netherlands (+31)" },
  { value: "nz", label: "New Zealand (+64)" },
  { value: "ng", label: "Nigeria (+234)" },
  { value: "pk", label: "Pakistan (+92)" },
  { value: "ph", label: "Philippines (+63)" },
  { value: "pl", label: "Poland (+48)" },
  { value: "ru", label: "Russia (+7)" },
  { value: "sa", label: "Saudi Arabia (+966)" },
  { value: "sg", label: "Singapore (+65)" },
  { value: "za", label: "South Africa (+27)" },
  { value: "kr", label: "South Korea (+82)" },
  { value: "es", label: "Spain (+34)" },
  { value: "se", label: "Sweden (+46)" },
  { value: "ch", label: "Switzerland (+41)" },
  { value: "th", label: "Thailand (+66)" },
  { value: "tr", label: "Turkey (+90)" },
  { value: "ae", label: "UAE (+971)" },
  { value: "gb", label: "United Kingdom (+44)" },
  { value: "us", label: "United States (+1)" },
  { value: "vn", label: "Vietnam (+84)" },
];
